### ISSUE TITLE
Align selection color with Emacs?

### ISSUE THREAD

**Issue by matklad** [matklad/pale-fire#11]
VS Code:

![image](https://user-images.githubusercontent.com/1711539/87664576-c2ad8f00-c765-11ea-8f00-861b866aa17e.png)

Emacs:

![image](https://user-images.githubusercontent.com/1711539/87664600-d22cd800-c765-11ea-8438-8e55e914207a.png)

I think Emacs approach of using *lighter* background is more readable

**Comment by arzg** [comment]
I agree, this is an improvement. Do you think this should apply everywhere, including the completion list?

**Comment by matklad** [comment]
Yeah, I guess it makes sense to do the same. Although emacs uses lighter backgound for completion:

![image](https://user-images.githubusercontent.com/1711539/87666694-5fbdf700-c769-11ea-8de7-674815e38baa.png)

**Comment by arzg** [comment]
The Emacs example you gave has the same background for the list as the editor – `#3f3f3f` – while in VS Code lists are currently one colour darker – `#383838`. The highlighted line in Emacs is `#4f4f4f`.

Here is a screenshot of a VS Code list using `#4f4f4f` with the `#383838` background. Notice how the focused item has a stronger highlight than in Emacs, due to the darker background in VS Code leading to a higher contrast.

<img width="1136" alt="Screen Shot 2020-07-16 at 9 33 23 pm" src="https://user-images.githubusercontent.com/31783266/87666513-1642cb80-c7ac-11ea-9154-85a9f7a967d0.png">

Here is VS Code using `#494949` as the highlight colour, compensating for the darker background. I would say that this has a closer match to Emacs in terms of the ‘strength’ of the highlighted item.

<img width="1136" alt="Screen Shot 2020-07-16 at 9 33 33 pm" src="https://user-images.githubusercontent.com/31783266/87666530-1c38ac80-c7ac-11ea-8b10-a82dda3f7982.png">

I’d say that it isn’t a good idea to match VS Code lists’ backgrounds to Emacs, as making the background the same removes the vital separation between the editor and the list, making it less easy to separate the two.

A screenshot with `#3f3f3f` as the background and `#4f4f4f` for the highlighted item.

<img width="1136" alt="Screen Shot 2020-07-16 at 9 42 43 pm" src="https://user-images.githubusercontent.com/31783266/87667204-49d22580-c7ad-11ea-9780-d23a7d07a8a7.png">

**Comment by arzg** [comment]
> Yeah, I guess it makes sense to do the same. Although emacs uses lighter backgound for completion:
> 
> ![image](https://user-images.githubusercontent.com/1711539/87666694-5fbdf700-c769-11ea-8de7-674815e38baa.png)

This is pretty interesting.

The current setup:

- **background**: `#383838` (zenburn-bg-05)
- **selection**: `#2B2B2B` (zenburn-bg-1)
- **matched text**: `#BDE0F3` (zenburn-blue+3)

<img width="1136" alt="Screen Shot 2020-07-16 at 9 43 59 pm" src="https://user-images.githubusercontent.com/31783266/87667303-76863d00-c7ad-11ea-8ffe-63c751347ade.png">

Emacs-like:

- **background**: `#4F4F4F` (zenburn-bg+1)
- **selection**: `#2B2B2B` (zenburn-bg-1)
- **matched text**: `#8FB28F` (zenburn-green+1)
<img width="1136" alt="Screen Shot 2020-07-16 at 9 50 00 pm" src="https://user-images.githubusercontent.com/31783266/87667799-4f7c3b00-c7ae-11ea-8325-c4aaf55dd40b.png">

**Comment by arzg** [comment]
Also, this is pretty unrelated, but I’ve been wondering if it’s at all possible to change the colour of the blue ‘recently used’ text in the command palette.

**Comment by matklad** [comment]
For menu items, I think either version is better than the status quo, but I don't know which one is the best. In general, I am pretty bad at deciding which colors I like, I am only capable of stealing from Emacs :)

For completion, I think I like emacs flavor slightly more.

@arzg in general, feel free to just implement whatever you feel best -- I usually don't have strong feelings, and, even if I had,  I'd just open a PR :)

**Comment by arzg** [comment]
> For menu items, I think either version is better than the status quo, but I don't know which one is the best. In general, I am pretty bad at deciding which colors I like, I am only capable of stealing from Emacs :)
> 
> For completion, I think I like emacs flavor slightly more.

Ok, I think I’ll implement the higher contrast list style, with the Emacs completion menu style. I might end up switching the matched text from green back to blue, because at the moment I prefer the stronger emphasis it provides.

> @arzg in general, feel free to just implement whatever you feel best -- I usually don't have strong feelings, and, even if I had, I'd just open a PR :)

:)

**Comment by arzg** [comment]
Actually, I just tried Emacs’ completion list settings again and I’m undecided. I feel like the selected item has too much emphasis.

I was wondering what you’d think of using the same settings for the completion list as for other lists, e.g. the file explorer or the command palette?

**Comment by arzg** [comment]
Some screenshots using this symmetry:

<img width="602" alt="Screen Shot 2020-07-17 at 8 58 15 pm" src="https://user-images.githubusercontent.com/31783266/87779516-3d62d100-c870-11ea-9124-694c7b07327c.png">
<img width="482" alt="Screen Shot 2020-07-17 at 8 58 26 pm" src="https://user-images.githubusercontent.com/31783266/87779529-43f14880-c870-11ea-8b8d-d55c4b91df33.png">

**Comment by matklad** [comment]
I think vscode uses the same style for both by default, right? than it's a good reason to stick with this approach as well

**Comment by arzg** [comment]
> I think vscode uses the same style for both by default, right? than it's a good reason to stick with this approach as well

I’m not sure if that’s what VS Code does, but I like it, so I guess that’s what I’ll do.

**Comment by arzg** [comment]
Turns out that you don’t even need to set any settings for the completion list – by default it just takes colours from lists!
