### ISSUE TITLE
hc version breaks vs code?

### ISSUE THREAD

**Issue by matklad** [matklad/pale-fire#26]
https://user-images.githubusercontent.com/1711539/103999271-bc94ea00-51ad-11eb-9fa8-05adff0c42ed.mp4

**Comment by arzg** [comment]
That is really, really weird. I can reproduce this, but I think the reason I didn’t catch this while I was making the theme is because I was in VS Code’s Extension Development Host (the thing where where you press <kbd>F5</kbd> while you have a theme file open and another window opens), which doesn’t have this problem.

https://user-images.githubusercontent.com/31783266/104001630-0ef8f980-51f4-11eb-9e0a-2022dfe5d866.mov

_Note how the window title has the text ‘[Extension Development Host]’._

The JSON files seem fine on inspection, and `package.json` seems fine too. Any ideas how to fix this?
