### ISSUE TITLE
Two highlight color opacity levels in the git commit message box

### ISSUE THREAD

**Issue by Cldfire** [matklad/pale-fire#32]
![image](https://user-images.githubusercontent.com/13814214/109216448-8bcf3b00-7782-11eb-8759-501f8a18a0f7.png)

Note the odd trailing gray color behind each highlighted line. Not sure why that's appearing, but it doesn't display like that in other themes :thinking:

**Comment by arzg** [comment]
Hmm, I can reproduce.

I think I know what the issue is: editor selections are set to be dark grey, while selections in the UI are set to be white with a low opacity. We know the editor background colour for sure, so we can set the editor selection colour specifically; in UI, though, the background colour can vary. By using a colour with low opacity, we allow the selection colour to adapt to the background.

What I think you’re seeing here is the Git commit message editor somehow overlaying ‘code editor’ functionality on top of ‘UI text box’ functionality, which leads to two selections being displayed.

I see two ‘solutions’ here:

- ignore the problem and just live with it
- use the same colour for UI selections as editor selections, and live with the selection having too little contrast in some scenarios
- change the editor selection colour to be the same as UI selections

**Comment by Cldfire** [comment]
Ignoring it could work if the other options lead to worse results, it's not that big of a deal :slightly_smiling_face:.

**Comment by Cldfire** [comment]
This isn't an issue anymore :raised_hands:
