### ISSUE TITLE
Dim out injected items

### ISSUE THREAD

**Issue by matklad** [matklad/pale-fire#37]
![image](https://user-images.githubusercontent.com/1711539/118536202-1a38d480-b754-11eb-808e-08e50caf9da0.png)

would be useful to mark such items somehow, especially in rust-analyzer's own tests

![image](https://user-images.githubusercontent.com/1711539/118536284-33da1c00-b754-11eb-854e-3ff009a5a7c5.png)

**Comment by arzg** [comment]
I don’t think there’s a way to tell VS Code the opacity a given semantic token modifier should apply _on top of_ any pre-existing highlighting. We could compute at theme-generation time what the lower opacity colours would render as, and then use these for `injected` versions of all existing semantic token highlighting. This is a lot of effort for (IMO) a minor change. If differentiation, not deemphasisation, is what you want, then maybe italics will do?

<img width="577" alt="Screen Shot 2021-09-10 at 5 58 35 pm" src="https://user-images.githubusercontent.com/31783266/132820532-88e6edd8-b560-4927-ac3d-8b4d49041801.png">

**Comment by arzg** [comment]
I’ve implemented this in 1d918e9; here’s what it looks like:

<img alt="Screen Shot 2021-11-25 at 2 35 39 pm" src="https://user-images.githubusercontent.com/31783266/143375440-1a6a3f83-11bb-40cb-83f9-8c5133730b62.png">

Colour theme generator code quality aside (for the moment it’s leaking memory; since it’s only run by theme developers, not end-users I thought it’s worth getting this feature done before updating the `mottle` theme generator library to make the `Box::leak` call unnecessary), this works perfectly.

However, It seems that rust-analyzer doesn’t emit the `injected` semantic token modifier for injected highlighting in rust-analyser’s tests, so they don’t get dimmed. Is this intentional?
